## Project Backlog
### 1. Project Setup
* Choose the dataset

* Define research questions

* Create GitHub repository

* Assign responsibilities


### 2. Data Cleaning
* Load dataset

* Check missing values

* Remove duplicates

* Convert data types

* Export cleaned dataset

### 3. Univariate EDA
* Summary statistics

* Histograms

* Boxplots

* Bar charts

* Conclusions

### 4. Bivariate EDA
* GroupBy

* Crosstab

* Scatterplots

* Correlation

* Conclusions

### 5. SQL
* Import dataset

* Create table

* Write queries

* Save queries

### 6. Documentation
* README

* Notebook comments

* Conclusions

### 7. Presentation
* Slides

* Assign speakers

* Practice

### 8. Final Review
* Merge branches

* Final checks

* Submit

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

In [4]:
df = pd.read_csv("dataset/football_matches_dataset.csv")

In [5]:
df.head()

,Unnamed: 0,home_team,away_team,date,league,season,home_score,away_score,home_xg,away_xg,...,home_defense_rating_last_2_home_matches,away_defense_rating_last_2_away_matches,home_midfield_rating_last_4_matches,away_midfield_rating_last_4_matches,home_midfield_rating_last_2_home_matches,away_midfield_rating_last_2_away_matches,home_attack_rating_last_4_matches,away_attack_rating_last_4_matches,home_attack_rating_last_2_home_matches,away_attack_rating_last_2_away_matches
0,0,Reims,Paris Saint Germain,August 08 2014,Ligue 1,2014/2015,2,2,1.37,2.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Evian Thonon Gaillard,Caen,August 09 2014,Ligue 1,2014/2015,0,3,0.81,1.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Guingamp,Saint-Etienne,August 09 2014,Ligue 1,2014/2015,0,2,0.63,1.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Lille,Metz,August 09 2014,Ligue 1,2014/2015,0,0,1.54,0.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Montpellier,Bordeaux,August 09 2014,Ligue 1,2014/2015,0,1,1.02,0.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.shape

(16332, 55)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16332 entries, 0 to 16331
Data columns (total 55 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Unnamed: 0                                16332 non-null  int64
 1   home_team                                 16332 non-null  object
 2   away_team                                 16332 non-null  object
 3   date                                      16332 non-null  object
 4   league                                    16332 non-null  object
 5   season                                    16332 non-null  object
 6   home_score                                16332 non-null  int64
 7   away_score                                16332 non-null  int64
 8   home_xg                                   16332 non-null  float64
 9   away_xg                                   16332 non-null  float64
 10  datetime                                  16332 non-null  object
 11  home_standings                            16332 non-null  int64
 12  away_standings                            16332 non-null  int64
 13  home_points                               16332 non-null  int64
 14  away_points                               16332 non-null  int64
 15  home_points_last_4_matches                16020 non-null  float64
 16  away_points_last_4_matches                16016 non-null  float64
 17  home_points_last_2_home_matches           16018 non-null  float64
 18  away_points_last_2_away_matches           16018 non-null  float64
 19  home_goals_last_4_matches                 16020 non-null  float64
 20  away_goals_last_4_matches                 16016 non-null  float64
 21  home_goals_last_2_home_matches            16018 non-null  float64
 22  away_goals_last_2_away_matches            16018 non-null  float64
 23  home_goals_against_last_4_matches         16020 non-null  float64
 24  away_goals_against_last_4_matches         16016 non-null  float64
 25  home_goals_against_last_2_home_matches    16018 non-null  float64
 26  away_goals_against_last_2_away_matches    16018 non-null  float64
 27  home_mean_xg_last_4_matches               16020 non-null  float64
 28  away_mean_xg_last_4_matches               16016 non-null  float64
 29  home_mean_xg_last_2_home_matches          16018 non-null  float64
 30  away_mean_xg_last_2_away_matches          16018 non-null  float64
 31  home_mean_xg_against_last_4_matches       16020 non-null  float64
 32  away_mean_xg_against_last_4_matches       16016 non-null  float64
 33  home_mean_xg_against_last_2_home_matches  16018 non-null  float64
 34  away_mean_xg_against_last_2_away_matches  16018 non-null  float64
 35  home_formation                            16332 non-null  int64
 36  away_formation                            16332 non-null  int64
 37  home_defense_rating                       16332 non-null  float64
 38  away_defense_rating                       16332 non-null  float64
 39  home_midfield_rating                      16332 non-null  float64
 40  away_midfield_rating                      16332 non-null  float64
 41  home_attack_rating                        16332 non-null  float64
 42  away_attack_rating                        16332 non-null  float64
 43  home_defense_rating_last_4_matches        16020 non-null  float64
 44  away_defense_rating_last_4_matches        16016 non-null  float64
 45  home_defense_rating_last_2_home_matches   16018 non-null  float64
 46  away_defense_rating_last_2_away_matches   16018 non-null  float64
 47  home_midfield_rating_last_4_matches       16020 non-null  float64
 48  away_midfield_rating_last_4_matches       16016 non-null  float64
 49  home_midfield_rating_last_2_home_matches  16018 non-null  float64
 50  away_midfield_rating_last_2_away_matches  16018 non-null  float64
 51  home_attack_rating_last_4_matches         16020 non-null  float64
 52  away_attack_rating_last_4_matches         16016 non-null  float64
 53  home_attack_rating_last_2_home_matches    16018 non-null  float64
 54  away_attack_rating_last_2_away_matches    16018 non-null  float64
dtypes: float64(40), int64(9), object(6)
memory usage: 6.9+ MB

In [9]:
list(df.columns)

['Unnamed: 0',
 'home_team',
 'away_team',
 'date',
 'league',
 'season',
 'home_score',
 'away_score',
 'home_xg',
 'away_xg',
 'datetime',
 'home_standings',
 'away_standings',
 'home_points',
 'away_points',
 'home_points_last_4_matches',
 'away_points_last_4_matches',
 'home_points_last_2_home_matches',
 'away_points_last_2_away_matches',
 'home_goals_last_4_matches',
 'away_goals_last_4_matches',
 'home_goals_last_2_home_matches',
 'away_goals_last_2_away_matches',
 'home_goals_against_last_4_matches',
 'away_goals_against_last_4_matches',
 'home_goals_against_last_2_home_matches',
 'away_goals_against_last_2_away_matches',
 'home_mean_xg_last_4_matches',
 'away_mean_xg_last_4_matches',
 'home_mean_xg_last_2_home_matches',
 'away_mean_xg_last_2_away_matches',
 'home_mean_xg_against_last_4_matches',
 'away_mean_xg_against_last_4_matches',
 'home_mean_xg_against_last_2_home_matches',
 'away_mean_xg_against_last_2_away_matches',
 'home_formation',
 'away_formation',
 'home_defense_rating',
 'away_defense_rating',
 'home_midfield_rating',
 'away_midfield_rating',
 'home_attack_rating',
 'away_attack_rating',
 'home_defense_rating_last_4_matches',
 'away_defense_rating_last_4_matches',
 'home_defense_rating_last_2_home_matches',
 'away_defense_rating_last_2_away_matches',
 'home_midfield_rating_last_4_matches',
 'away_midfield_rating_last_4_matches',
 'home_midfield_rating_last_2_home_matches',
 'away_midfield_rating_last_2_away_matches',
 'home_attack_rating_last_4_matches',
 'away_attack_rating_last_4_matches',
 'home_attack_rating_last_2_home_matches',
 'away_attack_rating_last_2_away_matches']

MISSING Values

In [10]:
df.isnull().sum()

Unnamed: 0                                    0
home_team                                     0
away_team                                     0
date                                          0
league                                        0
season                                        0
home_score                                    0
away_score                                    0
home_xg                                       0
away_xg                                       0
datetime                                      0
home_standings                                0
away_standings                                0
home_points                                   0
away_points                                   0
home_points_last_4_matches                  312
away_points_last_4_matches                  316
home_points_last_2_home_matches             314
away_points_last_2_away_matches             314
home_goals_last_4_matches                   312
away_goals_last_4_matches                   316
home_goals_last_2_home_matches              314
away_goals_last_2_away_matches              314
home_goals_against_last_4_matches           312
away_goals_against_last_4_matches           316
home_goals_against_last_2_home_matches      314
away_goals_against_last_2_away_matches      314
home_mean_xg_last_4_matches                 312
away_mean_xg_last_4_matches                 316
home_mean_xg_last_2_home_matches            314
away_mean_xg_last_2_away_matches            314
home_mean_xg_against_last_4_matches         312
away_mean_xg_against_last_4_matches         316
home_mean_xg_against_last_2_home_matches    314
away_mean_xg_against_last_2_away_matches    314
home_formation                                0
away_formation                                0
home_defense_rating                           0
away_defense_rating                           0
home_midfield_rating                          0
away_midfield_rating                          0
home_attack_rating                            0
away_attack_rating                            0
home_defense_rating_last_4_matches          312
away_defense_rating_last_4_matches          316
home_defense_rating_last_2_home_matches     314
away_defense_rating_last_2_away_matches     314
home_midfield_rating_last_4_matches         312
away_midfield_rating_last_4_matches         316
home_midfield_rating_last_2_home_matches    314
away_midfield_rating_last_2_away_matches    314
home_attack_rating_last_4_matches           312
away_attack_rating_last_4_matches           316
home_attack_rating_last_2_home_matches      314
away_attack_rating_last_2_away_matches      314
dtype: int64

In [11]:
missing = df.isnull().sum()     #check

missing_percentage = (missing / len(df)) * 100

pd.DataFrame({
    "Missing Values": missing,
    "Percentage": missing_percentage.round(2)
}).sort_values("Missing Values", ascending=False)

                                          Missing Values  Percentage
away_points_last_4_matches                           316        1.93
away_attack_rating_last_4_matches                    316        1.93
away_goals_against_last_4_matches                    316        1.93
away_midfield_rating_last_4_matches                  316        1.93
away_goals_last_4_matches                            316        1.93
away_defense_rating_last_4_matches                   316        1.93
away_mean_xg_last_4_matches                          316        1.93
away_mean_xg_against_last_4_matches                  316        1.93
away_attack_rating_last_2_away_matches               314        1.92
away_goals_against_last_2_away_matches               314        1.92
home_goals_against_last_2_home_matches               314        1.92
away_mean_xg_last_2_away_matches                     314        1.92
away_goals_last_2_away_matches                       314        1.92
home_goals_last_2_home_matches                       314        1.92
away_points_last_2_away_matches                      314        1.92
home_points_last_2_home_matches                      314        1.92
home_mean_xg_against_last_2_home_matches             314        1.92
away_mean_xg_against_last_2_away_matches             314        1.92
home_defense_rating_last_2_home_matches              314        1.92
away_defense_rating_last_2_away_matches              314        1.92
home_midfield_rating_last_2_home_matches             314        1.92
away_midfield_rating_last_2_away_matches             314        1.92
home_attack_rating_last_2_home_matches               314        1.92
home_mean_xg_last_2_home_matches                     314        1.92
home_defense_rating_last_4_matches                   312        1.91
home_mean_xg_against_last_4_matches                  312        1.91
home_midfield_rating_last_4_matches                  312        1.91
home_attack_rating_last_4_matches                    312        1.91
home_mean_xg_last_4_matches                          312        1.91
home_goals_last_4_matches                            312        1.91
home_points_last_4_matches                           312        1.91
home_goals_against_last_4_matches                    312        1.91
home_team                                              0        0.00
home_standings                                         0        0.00
away_team                                              0        0.00
date                                                   0        0.00
league                                                 0        0.00
season                                                 0        0.00
home_score                                             0        0.00
away_score                                             0        0.00
home_xg                                                0        0.00
away_xg                                                0        0.00
datetime                                               0        0.00
away_attack_rating                                     0        0.00
away_standings                                         0        0.00
home_attack_rating                                     0        0.00
away_midfield_rating                                   0        0.00
home_midfield_rating                                   0        0.00
away_defense_rating                                    0        0.00
home_defense_rating                                    0        0.00
away_formation                                         0        0.00
home_formation                                         0        0.00
home_points                                            0        0.00
away_points                                            0        0.00
Unnamed: 0                                             0        0.00

In [5]:
clean_df = df.drop(columns=["Unnamed: 0"])

In [6]:
clean_df["datetime"] = pd.to_datetime(clean_df["datetime"])

In [8]:
# Create total_goals
clean_df["total_goals"] = clean_df["home_score"] + clean_df["away_score"]

# Create total_xg
clean_df["total_xg"] = clean_df["home_xg"] + clean_df["away_xg"]
print(clean_df.columns.tolist())

['home_team', 'away_team', 'date', 'league', 'season', 'home_score', 'away_score', 'home_xg', 'away_xg', 'datetime', 'home_standings', 'away_standings', 'home_points', 'away_points', 'home_points_last_4_matches', 'away_points_last_4_matches', 'home_points_last_2_home_matches', 'away_points_last_2_away_matches', 'home_goals_last_4_matches', 'away_goals_last_4_matches', 'home_goals_last_2_home_matches', 'away_goals_last_2_away_matches', 'home_goals_against_last_4_matches', 'away_goals_against_last_4_matches', 'home_goals_against_last_2_home_matches', 'away_goals_against_last_2_away_matches', 'home_mean_xg_last_4_matches', 'away_mean_xg_last_4_matches', 'home_mean_xg_last_2_home_matches', 'away_mean_xg_last_2_away_matches', 'home_mean_xg_against_last_4_matches', 'away_mean_xg_against_last_4_matches', 'home_mean_xg_against_last_2_home_matches', 'away_mean_xg_against_last_2_away_matches', 'home_formation', 'away_formation', 'home_defense_rating', 'away_defense_rating', 'home_midfield_rating', 'away_midfield_rating', 'home_attack_rating', 'away_attack_rating', 'home_defense_rating_last_4_matches', 'away_defense_rating_last_4_matches', 'home_defense_rating_last_2_home_matches', 'away_defense_rating_last_2_away_matches', 'home_midfield_rating_last_4_matches', 'away_midfield_rating_last_4_matches', 'home_midfield_rating_last_2_home_matches', 'away_midfield_rating_last_2_away_matches', 'home_attack_rating_last_4_matches', 'away_attack_rating_last_4_matches', 'home_attack_rating_last_2_home_matches', 'away_attack_rating_last_2_away_matches', 'total_goals', 'total_xg']

In [9]:
clean_df.head()

,home_team,away_team,date,league,season,home_score,away_score,home_xg,away_xg,datetime,...,home_midfield_rating_last_4_matches,away_midfield_rating_last_4_matches,home_midfield_rating_last_2_home_matches,away_midfield_rating_last_2_away_matches,home_attack_rating_last_4_matches,away_attack_rating_last_4_matches,home_attack_rating_last_2_home_matches,away_attack_rating_last_2_away_matches,total_goals,total_xg
0,Reims,Paris Saint Germain,August 08 2014,Ligue 1,2014/2015,2,2,1.37,2.66,2014-08-08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4.03
1,Evian Thonon Gaillard,Caen,August 09 2014,Ligue 1,2014/2015,0,3,0.81,1.24,2014-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2.05
2,Guingamp,Saint-Etienne,August 09 2014,Ligue 1,2014/2015,0,2,0.63,1.50,2014-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.13
3,Lille,Metz,August 09 2014,Ligue 1,2014/2015,0,0,1.54,0.06,2014-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.60
4,Montpellier,Bordeaux,August 09 2014,Ligue 1,2014/2015,0,1,1.02,0.75,2014-08-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.77