In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("leonidkiselev/football-matches-statistics")

print("Path to dataset files:", path)

Downloading to C:\Users\M. Grillo\.cache\kagglehub\datasets\leonidkiselev\football-matches-statistics\2.archive...

100%|██████████| 11.0M/11.0M [00:02<00:00, 4.47MB/s]

Extracting files...

Path to dataset files: C:\Users\M. Grillo\.cache\kagglehub\datasets\leonidkiselev\football-matches-statistics\versions\2

ist 2014 bis 2022

In [ ]:
import pandas as pd

# 1. Daten einlesen
df_matches = df
df_players = dfc

# 2. Schlüsselspalten definieren
# Da die Spaltennamen in beiden Heads exakt übereinstimmen (home_team, away_team, season),
# können wir sie direkt als Liste übergeben.
merge_keys = ['home_team', 'away_team', 'season']
df_matches_bl = df_matches[df_matches['league'] == 'Bundesliga'].iloc[:, :12].copy()

# 3. Zusammenführen (Left-Merge an die Spieler-Statistiken)
df_combined = pd.merge(
    df_players, 
    df_matches, 
    on=merge_keys, 
    how='inner'
)

# Kontroll-Check
print(f"Zeilen im Spieler-DF: {len(df_players)}")
print(f"Zeilen im kombinierten DF: {len(df_combined)}")

df_combined.head(35)

df_combined.iloc[72:73].match_url
df_players.position.unique()

Zeilen im Spieler-DF: 640501
Zeilen im kombinierten DF: 103575

array(['DC', 'DL', 'DR', 'FW', 'GK', 'MC', 'ML', 'MR', 'Sub', 'FWL',
       'FWR', 'AMC', 'DMC', 'AML', 'AMR', 'DML', 'DMR'], dtype=object)

In [2]:
import pandas as pd

df = pd.read_csv("./dataset/football_matches_dataset.csv")
dfc = pd.read_csv("./dataset/ratings.csv")

#df.info()
dfc.info()
df.head(4)
#df.describe()
#df.home_team.head(58)
#df.league.unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640501 entries, 0 to 640500
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Unnamed: 0    640501 non-null  int64
 1   match_url     640501 non-null  object
 2   player        640501 non-null  object
 3   position      640501 non-null  object
 4   rating        467518 non-null  float64
 5   home_team     640501 non-null  object
 6   away_team     640501 non-null  object
 7   season        640501 non-null  object
 8   home_or_away  640501 non-null  object
 9   datetime      640501 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 48.9+ MB

,Unnamed: 0,home_team,away_team,date,league,season,home_score,away_score,home_xg,away_xg,...,home_defense_rating_last_2_home_matches,away_defense_rating_last_2_away_matches,home_midfield_rating_last_4_matches,away_midfield_rating_last_4_matches,home_midfield_rating_last_2_home_matches,away_midfield_rating_last_2_away_matches,home_attack_rating_last_4_matches,away_attack_rating_last_4_matches,home_attack_rating_last_2_home_matches,away_attack_rating_last_2_away_matches
0,0,Reims,Paris Saint Germain,August 08 2014,Ligue 1,2014/2015,2,2,1.37,2.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Evian Thonon Gaillard,Caen,August 09 2014,Ligue 1,2014/2015,0,3,0.81,1.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Guingamp,Saint-Etienne,August 09 2014,Ligue 1,2014/2015,0,2,0.63,1.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Lille,Metz,August 09 2014,Ligue 1,2014/2015,0,0,1.54,0.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df_matches_bl = df_matches[df_matches['league'] == 'Bundesliga'].iloc[:, :12]
df_matches_bl

,Unnamed: 0,home_team,away_team,date,league,season,home_score,away_score,home_xg,away_xg,datetime,home_standings
30,30,Bayern Munich,Wolfsburg,August 22 2014,Bundesliga,2014/2015,2,1,2.57,1.20,2014-08-22,3
34,34,Borussia Dortmund,Bayer Leverkusen,August 23 2014,Bundesliga,2014/2015,0,2,0.48,1.15,2014-08-23,4
37,37,Eintracht Frankfurt,Freiburg,August 23 2014,Bundesliga,2014/2015,1,0,1.75,1.38,2014-08-23,5
39,39,FC Cologne,Hamburger SV,August 23 2014,Bundesliga,2014/2015,0,0,0.52,0.91,2014-08-23,6
42,42,Hannover 96,Schalke 04,August 23 2014,Bundesliga,2014/2015,2,1,1.18,0.96,2014-08-23,8
...,...,...,...,...,...,...,...,...,...,...,...,...
16260,16260,FC Cologne,Bayern Munich,May 27 2023,Bundesliga,2022/2023,1,2,1.16,1.68,2023-05-27,11
16268,16268,RasenBallsport Leipzig,Schalke 04,May 27 2023,Bundesliga,2022/2023,4,2,2.97,1.22,2023-05-27,3
16275,16275,Union Berlin,Werder Bremen,May 27 2023,Bundesliga,2022/2023,1,0,0.78,0.40,2023-05-27,4
16276,16276,VfB Stuttgart,Hoffenheim,May 27 2023,Bundesliga,2022/2023,1,1,2.19,1.16,2023-05-27,16
16277,16277,Wolfsburg,Hertha Berlin,May 27 2023,Bundesliga,2022/2023,1,2,3.21,1.44,2023-05-27,8