## Project Backlog
### 1. Project Setup
* Choose the dataset

* Define research questions

* Create GitHub repository

* Assign responsibilities


### 2. Data Cleaning
* Load dataset

* Check missing values

* Remove duplicates

* Convert data types

* Export cleaned dataset

### 3. Univariate EDA
* Summary statistics

* Histograms

* Boxplots

* Bar charts

* Conclusions

### 4. Bivariate EDA
* GroupBy

* Crosstab

* Scatterplots

* Correlation

* Conclusions

### 5. SQL
* Import dataset

* Create table

* Write queries

* Save queries

### 6. Documentation
* README

* Notebook comments

* Conclusions

### 7. Presentation
* Slides

* Assign speakers

* Practice

### 8. Final Review
* Merge branches

* Final checks

* Submit

### 1. Project Setup

### Questions - Targets
1. How accurately do Expected Goals (xG) predict the final match result?
Why? Expected Goals (xG) is one of the most important metrics in modern football
analytics.
Main Variables: Home xG, Away xG, Home Goals, Away Goals, League, Season.
Possible Analysis: Correlation between xG and goals, comparison across leagues and
seasons.
2. Does recent team performance influence match outcomes?
Why? The dataset contains extensive information about recent team performance.
Main Variables: Previous Points, Previous Goals Scored, Previous Goals Conceded,
Previous xG, Match Result, League.
Possible Analysis: Team form, winning probability and performance trends.
3. Do teams with more current points consistently achieve better match results?
Why? Evaluate whether the number of points accumulated before a match predicts
future performance.
Main Variables: Current Points, Goals, xG, Match Result, League, Season.
Possible Analysis: Current points vs wins, goals and Expected Goals.
4. How do team player ratings and team formations influence match performance?
Why? Uses team-level player ratings together with tactical formations.
Main Variables: Team Player Ratings (Defense, Midfield, Attack), Formation, Goals, xG.
Possible Analysis: Ratings vs goals, ratings vs xG, best formations and league
comparisons.

5. Which league has the highest average Expected Goals (xG) per match?
6. Which league produces the highest average number of goals per match?
7. Is there a relationship between Expected Goals (xG) and actual goals scored?
8. Which league is the most competitive based on goal difference and match results?
9. Does home advantage vary across Europe's Top Five Leagues?
10. How does team form affect Expected Goals (xG) in future matches?
11. Which formations are associated with the highest attacking performance?
12. Do teams with higher player ratings consistently outperform lower-rated teams?

In [16]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

%matplotlib inline

In [17]:
df = pd.read_csv(r"C:\Users\cici\Documents\Ironhack\week 3\D3\project_2\prj-2-eda-sql-football-matches-statistics\dataset\football_matches_dataset.csv")

In [18]:
df.shape

(16332, 55)

In [25]:
df.head()

,Unnamed: 0,home_team,away_team,date,league,season,home_score,away_score,home_xg,away_xg,...,home_defense_rating_last_2_home_matches,away_defense_rating_last_2_away_matches,home_midfield_rating_last_4_matches,away_midfield_rating_last_4_matches,home_midfield_rating_last_2_home_matches,away_midfield_rating_last_2_away_matches,home_attack_rating_last_4_matches,away_attack_rating_last_4_matches,home_attack_rating_last_2_home_matches,away_attack_rating_last_2_away_matches
0,0,Reims,Paris Saint Germain,August 08 2014,Ligue 1,2014/2015,2,2,1.37,2.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Evian Thonon Gaillard,Caen,August 09 2014,Ligue 1,2014/2015,0,3,0.81,1.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Guingamp,Saint-Etienne,August 09 2014,Ligue 1,2014/2015,0,2,0.63,1.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Lille,Metz,August 09 2014,Ligue 1,2014/2015,0,0,1.54,0.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Montpellier,Bordeaux,August 09 2014,Ligue 1,2014/2015,0,1,1.02,0.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 16332 entries, 0 to 16331
Data columns (total 55 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Unnamed: 0                                16332 non-null  int64
 1   home_team                                 16332 non-null  str
 2   away_team                                 16332 non-null  str
 3   date                                      16332 non-null  str
 4   league                                    16332 non-null  str
 5   season                                    16332 non-null  str
 6   home_score                                16332 non-null  int64
 7   away_score                                16332 non-null  int64
 8   home_xg                                   16332 non-null  float64
 9   away_xg                                   16332 non-null  float64
 10  datetime                                  16332 non-null  str
 11  home_standings                            16332 non-null  int64
 12  away_standings                            16332 non-null  int64
 13  home_points                               16332 non-null  int64
 14  away_points                               16332 non-null  int64
 15  home_points_last_4_matches                16020 non-null  float64
 16  away_points_last_4_matches                16016 non-null  float64
 17  home_points_last_2_home_matches           16018 non-null  float64
 18  away_points_last_2_away_matches           16018 non-null  float64
 19  home_goals_last_4_matches                 16020 non-null  float64
 20  away_goals_last_4_matches                 16016 non-null  float64
 21  home_goals_last_2_home_matches            16018 non-null  float64
 22  away_goals_last_2_away_matches            16018 non-null  float64
 23  home_goals_against_last_4_matches         16020 non-null  float64
 24  away_goals_against_last_4_matches         16016 non-null  float64
 25  home_goals_against_last_2_home_matches    16018 non-null  float64
 26  away_goals_against_last_2_away_matches    16018 non-null  float64
 27  home_mean_xg_last_4_matches               16020 non-null  float64
 28  away_mean_xg_last_4_matches               16016 non-null  float64
 29  home_mean_xg_last_2_home_matches          16018 non-null  float64
 30  away_mean_xg_last_2_away_matches          16018 non-null  float64
 31  home_mean_xg_against_last_4_matches       16020 non-null  float64
 32  away_mean_xg_against_last_4_matches       16016 non-null  float64
 33  home_mean_xg_against_last_2_home_matches  16018 non-null  float64
 34  away_mean_xg_against_last_2_away_matches  16018 non-null  float64
 35  home_formation                            16332 non-null  int64
 36  away_formation                            16332 non-null  int64
 37  home_defense_rating                       16332 non-null  float64
 38  away_defense_rating                       16332 non-null  float64
 39  home_midfield_rating                      16332 non-null  float64
 40  away_midfield_rating                      16332 non-null  float64
 41  home_attack_rating                        16332 non-null  float64
 42  away_attack_rating                        16332 non-null  float64
 43  home_defense_rating_last_4_matches        16020 non-null  float64
 44  away_defense_rating_last_4_matches        16016 non-null  float64
 45  home_defense_rating_last_2_home_matches   16018 non-null  float64
 46  away_defense_rating_last_2_away_matches   16018 non-null  float64
 47  home_midfield_rating_last_4_matches       16020 non-null  float64
 48  away_midfield_rating_last_4_matches       16016 non-null  float64
 49  home_midfield_rating_last_2_home_matches  16018 non-null  float64
 50  away_midfield_rating_last_2_away_matches  16018 non-null  float64
 51  home_attack_rating_last_4_matches         16020 non-null  float64
 52  away_attack_rating_last_4_matches         16016 non-null  float64
 53  home_attack_rating_last_2_home_matches    16018 non-null  float64
 54  away_attack_rating_last_2_away_matches    16018 non-null  float64
dtypes: float64(40), int64(9), str(6)
memory usage: 6.9 MB

<span style="color:red"> Missing around 300 !!

<span style="color:red"> and date is a string, we shoukd tranform it to datetime

In [28]:
round(df.describe().T, 2)

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,16332.0,8165.50,4714.79,0.00,4082.75,8165.50,12248.25,16331.00
home_score,16332.0,1.54,1.31,0.00,1.00,1.00,2.00,10.00
away_score,16332.0,1.21,1.17,0.00,0.00,1.00,2.00,9.00
home_xg,16332.0,1.52,0.90,0.00,0.85,1.36,2.03,6.88
away_xg,16332.0,1.20,0.79,0.00,0.60,1.05,1.62,6.50
home_standings,16332.0,10.78,5.59,1.00,6.00,11.00,16.00,20.00
away_standings,16332.0,10.65,5.57,1.00,6.00,11.00,15.00,20.00
home_points,16332.0,24.71,17.92,0.00,10.00,22.00,36.00,94.00
away_points,16332.0,24.90,17.90,0.00,11.00,22.00,36.00,97.00
home_points_last_4_matches,16020.0,5.44,2.94,0.00,3.00,5.00,7.00,12.00
away_points_last_4_matches,16016.0,5.60,2.95,0.00,3.00,6.00,7.00,12.00
home_points_last_2_home_matches,16018.0,3.18,1.95,0.00,1.00,3.00,4.00,6.00
away_points_last_2_away_matches,16018.0,2.34,1.89,0.00,1.00,3.00,4.00,6.00
home_goals_last_4_matches,16020.0,5.45,2.87,0.00,3.00,5.00,7.00,22.00
away_goals_last_4_matches,16016.0,5.58,2.90,0.00,3.00,5.00,7.00,21.00
home_goals_last_2_home_matches,16018.0,3.08,1.98,0.00,2.00,3.00,4.00,14.00
away_goals_last_2_away_matches,16018.0,2.43,1.74,0.00,1.00,2.00,3.00,13.00
home_goals_against_last_4_matches,16020.0,5.54,2.67,0.00,4.00,5.00,7.00,19.00
away_goals_against_last_4_matches,16016.0,5.43,2.66,0.00,4.00,5.00,7.00,19.00
home_goals_against_last_2_home_matches,16018.0,2.42,1.67,0.00,1.00,2.00,3.00,13.00
away_goals_against_last_2_away_matches,16018.0,3.07,1.90,0.00,2.00,3.00,4.00,13.00
home_mean_xg_last_4_matches,16020.0,1.35,0.53,0.19,0.97,1.26,1.64,4.55
away_mean_xg_last_4_matches,16016.0,1.37,0.53,0.18,0.99,1.30,1.66,4.63
home_mean_xg_last_2_home_matches,16018.0,1.52,0.69,0.11,1.02,1.42,1.90,5.70
away_mean_xg_last_2_away_matches,16018.0,1.20,0.61,0.07,0.76,1.10,1.53,4.85
home_mean_xg_against_last_4_matches,16020.0,1.37,0.48,0.20,1.02,1.33,1.67,4.03
away_mean_xg_against_last_4_matches,16016.0,1.34,0.48,0.19,1.00,1.29,1.64,3.80
home_mean_xg_against_last_2_home_matches,16018.0,1.19,0.58,0.04,0.76,1.11,1.54,4.50
away_mean_xg_against_last_2_away_matches,16018.0,1.52,0.67,0.06,1.02,1.43,1.92,4.90
home_formation,16332.0,0.94,1.13,0.00,0.00,0.00,2.00,4.00
away_formation,16332.0,0.94,1.14,0.00,0.00,0.00,2.00,4.00
home_defense_rating,16332.0,6.85,0.46,4.75,6.53,6.85,7.18,8.61
away_defense_rating,16332.0,6.76,0.48,4.41,6.44,6.74,7.09,8.57
home_midfield_rating,16332.0,6.96,0.51,5.26,6.61,6.93,7.28,9.40
away_midfield_rating,16332.0,6.80,0.49,5.12,6.46,6.76,7.10,9.13
home_attack_rating,16332.0,7.04,0.72,4.61,6.51,6.93,7.46,10.00
away_attack_rating,16332.0,6.85,0.67,4.97,6.36,6.72,7.22,10.00
home_defense_rating_last_4_matches,16020.0,6.80,0.26,5.72,6.62,6.80,6.98,7.86
away_defense_rating_last_4_matches,16016.0,6.81,0.27,5.75,6.62,6.80,6.99,7.97
home_defense_rating_last_2_home_matches,16018.0,6.85,0.34,5.37,6.62,6.85,7.08,8.16
away_defense_rating_last_2_away_matches,16018.0,6.76,0.35,5.33,6.52,6.75,7.00,7.94
home_midfield_rating_last_4_matches,16020.0,6.88,0.30,5.95,6.67,6.85,7.06,8.34
away_midfield_rating_last_4_matches,16016.0,6.89,0.30,5.93,6.68,6.87,7.08,8.46
home_midfield_rating_last_2_home_matches,16018.0,6.97,0.39,5.62,6.69,6.94,7.21,8.68
away_midfield_rating_last_2_away_matches,16018.0,6.80,0.37,5.57,6.54,6.78,7.03,8.72
home_attack_rating_last_4_matches,16020.0,6.94,0.41,5.80,6.64,6.89,7.18,9.29
away_attack_rating_last_4_matches,16016.0,6.95,0.42,5.86,6.66,6.90,7.19,9.29
home_attack_rating_last_2_home_matches,16018.0,7.04,0.55,5.66,6.65,6.98,7.36,9.65
away_attack_rating_last_2_away_matches,16018.0,6.85,0.51,5.54,6.48,6.78,7.15,9.64

In [26]:
df.nunique()

Unnamed: 0                                  16332
home_team                                     157
away_team                                     157
date                                         1655
league                                          5
season                                          9
home_score                                     11
away_score                                     10
home_xg                                       519
away_xg                                       454
datetime                                     1655
home_standings                                 20
away_standings                                 20
home_points                                    94
away_points                                    97
home_points_last_4_matches                     12
away_points_last_4_matches                     12
home_points_last_2_home_matches                 6
away_points_last_2_away_matches                 6
home_goals_last_4_matches                      22
away_goals_last_4_matches                      22
home_goals_last_2_home_matches                 15
away_goals_last_2_away_matches                 14
home_goals_against_last_4_matches              20
away_goals_against_last_4_matches              20
home_goals_against_last_2_home_matches         13
away_goals_against_last_2_away_matches         14
home_mean_xg_last_4_matches                  1787
away_mean_xg_last_4_matches                  1837
home_mean_xg_last_2_home_matches             1005
away_mean_xg_last_2_away_matches              895
home_mean_xg_against_last_4_matches          1707
away_mean_xg_against_last_4_matches          1701
home_mean_xg_against_last_2_home_matches      868
away_mean_xg_against_last_2_away_matches      966
home_formation                                  5
away_formation                                  5
home_defense_rating                          3770
away_defense_rating                          3916
home_midfield_rating                         3464
away_midfield_rating                         3447
home_attack_rating                           2138
away_attack_rating                           1995
home_defense_rating_last_4_matches           8701
away_defense_rating_last_4_matches           8671
home_defense_rating_last_2_home_matches      6175
away_defense_rating_last_2_away_matches      6509
home_midfield_rating_last_4_matches          9917
away_midfield_rating_last_4_matches          9778
home_midfield_rating_last_2_home_matches     6737
away_midfield_rating_last_2_away_matches     6856
home_attack_rating_last_4_matches            6039
away_attack_rating_last_4_matches            6061
home_attack_rating_last_2_home_matches       4016
away_attack_rating_last_2_away_matches       3770
dtype: int64

In [27]:
df.dtypes

Unnamed: 0                                    int64
home_team                                       str
away_team                                       str
date                                            str
league                                          str
season                                          str
home_score                                    int64
away_score                                    int64
home_xg                                     float64
away_xg                                     float64
datetime                                        str
home_standings                                int64
away_standings                                int64
home_points                                   int64
away_points                                   int64
home_points_last_4_matches                  float64
away_points_last_4_matches                  float64
home_points_last_2_home_matches             float64
away_points_last_2_away_matches             float64
home_goals_last_4_matches                   float64
away_goals_last_4_matches                   float64
home_goals_last_2_home_matches              float64
away_goals_last_2_away_matches              float64
home_goals_against_last_4_matches           float64
away_goals_against_last_4_matches           float64
home_goals_against_last_2_home_matches      float64
away_goals_against_last_2_away_matches      float64
home_mean_xg_last_4_matches                 float64
away_mean_xg_last_4_matches                 float64
home_mean_xg_last_2_home_matches            float64
away_mean_xg_last_2_away_matches            float64
home_mean_xg_against_last_4_matches         float64
away_mean_xg_against_last_4_matches         float64
home_mean_xg_against_last_2_home_matches    float64
away_mean_xg_against_last_2_away_matches    float64
home_formation                                int64
away_formation                                int64
home_defense_rating                         float64
away_defense_rating                         float64
home_midfield_rating                        float64
away_midfield_rating                        float64
home_attack_rating                          float64
away_attack_rating                          float64
home_defense_rating_last_4_matches          float64
away_defense_rating_last_4_matches          float64
home_defense_rating_last_2_home_matches     float64
away_defense_rating_last_2_away_matches     float64
home_midfield_rating_last_4_matches         float64
away_midfield_rating_last_4_matches         float64
home_midfield_rating_last_2_home_matches    float64
away_midfield_rating_last_2_away_matches    float64
home_attack_rating_last_4_matches           float64
away_attack_rating_last_4_matches           float64
home_attack_rating_last_2_home_matches      float64
away_attack_rating_last_2_away_matches      float64
dtype: object

In [21]:
df.isna().sum()

Unnamed: 0                                    0
home_team                                     0
away_team                                     0
date                                          0
league                                        0
season                                        0
home_score                                    0
away_score                                    0
home_xg                                       0
away_xg                                       0
datetime                                      0
home_standings                                0
away_standings                                0
home_points                                   0
away_points                                   0
home_points_last_4_matches                  312
away_points_last_4_matches                  316
home_points_last_2_home_matches             314
away_points_last_2_away_matches             314
home_goals_last_4_matches                   312
away_goals_last_4_matches                   316
home_goals_last_2_home_matches              314
away_goals_last_2_away_matches              314
home_goals_against_last_4_matches           312
away_goals_against_last_4_matches           316
home_goals_against_last_2_home_matches      314
away_goals_against_last_2_away_matches      314
home_mean_xg_last_4_matches                 312
away_mean_xg_last_4_matches                 316
home_mean_xg_last_2_home_matches            314
away_mean_xg_last_2_away_matches            314
home_mean_xg_against_last_4_matches         312
away_mean_xg_against_last_4_matches         316
home_mean_xg_against_last_2_home_matches    314
away_mean_xg_against_last_2_away_matches    314
home_formation                                0
away_formation                                0
home_defense_rating                           0
away_defense_rating                           0
home_midfield_rating                          0
away_midfield_rating                          0
home_attack_rating                            0
away_attack_rating                            0
home_defense_rating_last_4_matches          312
away_defense_rating_last_4_matches          316
home_defense_rating_last_2_home_matches     314
away_defense_rating_last_2_away_matches     314
home_midfield_rating_last_4_matches         312
away_midfield_rating_last_4_matches         316
home_midfield_rating_last_2_home_matches    314
away_midfield_rating_last_2_away_matches    314
home_attack_rating_last_4_matches           312
away_attack_rating_last_4_matches           316
home_attack_rating_last_2_home_matches      314
away_attack_rating_last_2_away_matches      314
dtype: int64

In [22]:
missing = df.isna().sum()
missing = missing[missing > 0]
missing

home_points_last_4_matches                  312
away_points_last_4_matches                  316
home_points_last_2_home_matches             314
away_points_last_2_away_matches             314
home_goals_last_4_matches                   312
away_goals_last_4_matches                   316
home_goals_last_2_home_matches              314
away_goals_last_2_away_matches              314
home_goals_against_last_4_matches           312
away_goals_against_last_4_matches           316
home_goals_against_last_2_home_matches      314
away_goals_against_last_2_away_matches      314
home_mean_xg_last_4_matches                 312
away_mean_xg_last_4_matches                 316
home_mean_xg_last_2_home_matches            314
away_mean_xg_last_2_away_matches            314
home_mean_xg_against_last_4_matches         312
away_mean_xg_against_last_4_matches         316
home_mean_xg_against_last_2_home_matches    314
away_mean_xg_against_last_2_away_matches    314
home_defense_rating_last_4_matches          312
away_defense_rating_last_4_matches          316
home_defense_rating_last_2_home_matches     314
away_defense_rating_last_2_away_matches     314
home_midfield_rating_last_4_matches         312
away_midfield_rating_last_4_matches         316
home_midfield_rating_last_2_home_matches    314
away_midfield_rating_last_2_away_matches    314
home_attack_rating_last_4_matches           312
away_attack_rating_last_4_matches           316
home_attack_rating_last_2_home_matches      314
away_attack_rating_last_2_away_matches      314
dtype: int64

yes

In [23]:
df.duplicated().sum()

np.int64(0)

<span style="color:lightgreen">  No dupicates !!

In [24]:
df.eq(' ').sum()

Unnamed: 0                                  0
home_team                                   0
away_team                                   0
date                                        0
league                                      0
season                                      0
home_score                                  0
away_score                                  0
home_xg                                     0
away_xg                                     0
datetime                                    0
home_standings                              0
away_standings                              0
home_points                                 0
away_points                                 0
home_points_last_4_matches                  0
away_points_last_4_matches                  0
home_points_last_2_home_matches             0
away_points_last_2_away_matches             0
home_goals_last_4_matches                   0
away_goals_last_4_matches                   0
home_goals_last_2_home_matches              0
away_goals_last_2_away_matches              0
home_goals_against_last_4_matches           0
away_goals_against_last_4_matches           0
home_goals_against_last_2_home_matches      0
away_goals_against_last_2_away_matches      0
home_mean_xg_last_4_matches                 0
away_mean_xg_last_4_matches                 0
home_mean_xg_last_2_home_matches            0
away_mean_xg_last_2_away_matches            0
home_mean_xg_against_last_4_matches         0
away_mean_xg_against_last_4_matches         0
home_mean_xg_against_last_2_home_matches    0
away_mean_xg_against_last_2_away_matches    0
home_formation                              0
away_formation                              0
home_defense_rating                         0
away_defense_rating                         0
home_midfield_rating                        0
away_midfield_rating                        0
home_attack_rating                          0
away_attack_rating                          0
home_defense_rating_last_4_matches          0
away_defense_rating_last_4_matches          0
home_defense_rating_last_2_home_matches     0
away_defense_rating_last_2_away_matches     0
home_midfield_rating_last_4_matches         0
away_midfield_rating_last_4_matches         0
home_midfield_rating_last_2_home_matches    0
away_midfield_rating_last_2_away_matches    0
home_attack_rating_last_4_matches           0
away_attack_rating_last_4_matches           0
home_attack_rating_last_2_home_matches      0
away_attack_rating_last_2_away_matches      0
dtype: int64

<span style="color:lightgreen">  Clean data !!

In [36]:
df['date'] = pd.to_datetime(df['date'], format='%B\n%d\n%Y')
df

,Unnamed: 0,home_team,away_team,date,league,season,home_score,away_score,home_xg,away_xg,...,home_defense_rating_last_2_home_matches,away_defense_rating_last_2_away_matches,home_midfield_rating_last_4_matches,away_midfield_rating_last_4_matches,home_midfield_rating_last_2_home_matches,away_midfield_rating_last_2_away_matches,home_attack_rating_last_4_matches,away_attack_rating_last_4_matches,home_attack_rating_last_2_home_matches,away_attack_rating_last_2_away_matches
0,0,Reims,Paris Saint Germain,2014-08-08,Ligue 1,2014/2015,2,2,1.37,2.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Evian Thonon Gaillard,Caen,2014-08-09,Ligue 1,2014/2015,0,3,0.81,1.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Guingamp,Saint-Etienne,2014-08-09,Ligue 1,2014/2015,0,2,0.63,1.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Lille,Metz,2014-08-09,Ligue 1,2014/2015,0,0,1.54,0.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Montpellier,Bordeaux,2014-08-09,Ligue 1,2014/2015,0,1,1.02,0.75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16327,16327,Real Sociedad,Sevilla,2023-06-04,La liga,2022/2023,2,1,2.35,0.46,...,6.823000,7.251000,6.894917,6.580000,6.963500,6.475000,6.868750,6.993333,6.572500,7.430000
16328,16328,Real Valladolid,Getafe,2023-06-04,La liga,2022/2023,0,0,0.69,0.28,...,6.379000,6.749000,6.475000,6.718125,6.503333,6.639167,6.565833,6.632500,6.913333,6.095000
16329,16329,Roma,Spezia,2023-06-04,Serie A,2022/2023,2,1,2.28,1.11,...,6.389167,6.616000,6.573208,6.521667,6.493750,6.450000,6.518750,6.217083,6.445000,6.186667
16330,16330,Udinese,Juventus,2023-06-04,Serie A,2022/2023,0,1,0.96,1.47,...,6.938333,6.699167,6.595208,6.913500,6.815417,6.780000,6.521250,6.256250,6.447500,6.397500
16331,16331,Villarreal,Atletico Madrid,2023-06-04,La liga,2022/2023,2,2,2.06,1.16,...,7.089000,6.725000,6.865833,7.063542,7.315000,6.823333,7.329167,7.593750,7.790000,7.005000

In [41]:
negative_goals = df[(df['home_score'] < 0) | (df['away_score'] < 0)]
negative_xg = df[(df['home_xg'] < 0) | (df['away_xg'] < 0)]
# invalid_rating = df[(df['rating'] < 0) | (df['rating'] > 10)]
valid_leagues = ['Ligue 1']
unexpected_leagues = df[~df['league'].isin(valid_leagues)]

print(negative_goals.shape[0])
print(negative_xg.shape[0])
print(unexpected_leagues.shape[0])

0
0
13014